Repository Divyarajsinh1312/Python, pull requests merged in 2022-10, with the labels that each got.

#3 Update 1.py
  Exercise/1.py
Labels: hactoberfest

#4 Update 1.Print.py
  Pogrammes/1.Print.py
Labels: hactoberfest, hactoberfest-accepted

#5 Update 1.Print.py
  Pogrammes/1.Print.py
Labels: hactoberfest, hactoberfest-accepted

#6 Update 9.pythagoras_theoram.py
  Practice Problem/9.pythagoras_theoram.py
Labels: hactoberfest, hactoberfest-accepted

#7 Update EPG.py
  EPG.py
Labels: hactoberfest, hactoberfest-accepted

#8 Update 1.Print.py
  Pogrammes/1.Print.py
Labels: hactoberfest, hactoberfest-accepted

#9 Update 5.variable.py
  Pogrammes/5.variable.py
Labels: hactoberfest, hactoberfest-accepted

#10 Update EPG.py
  EPG.py
Labels: hactoberfest, hactoberfest-accepted

#13 Update 12.area_calculator.py
  Practice Problem/12.area_calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 Create rock_papper.py
  Practice Problem/rock_papper.py
Labels: hacktoberfest, hacktoberfest-accepted

#16 Create GeneratingStrongPassword.py
  Practice Problem/GeneratingStrongPassword.py
Labels: hacktoberfest-accepted

#15 Create coin_toss.py
  Practice Problem/coin_toss.py
Labels: hacktoberfest-accepted

#17 Create hollow_star_pyramid.py
  Practice Problem/hollow_star_pyramid.py
Labels: hacktoberfest-accepted

#18 Create fahrenheit_to_celsius.py
  Pogrammes/fahrenheit_to_celsius.py
Labels: hacktoberfest-accepted

#19 merge and quick sort using recursion
  sort_recursion/merge.py
  sort_recursion/quick.py
Labels: hacktoberfest-accepted

#20 Create pattern_ using_turtle.py
  pattern_ using_turtle.py
Labels: hacktoberfest-accepted

#21 Create 3d heart
  Practice Problem/3d heart
Labels: hacktoberfest-accepted

#24 Create Date_Time.py
  Practice Problem/Date_Time.py
Labels: hacktoberfest-accepted

#25 Update Date_Time.py
  Practice Problem/Date_Time.py
Labels: hacktoberfest-accepted

#26 Create json.py
  json.py
Labels: hacktoberfest-accepted

#27 Create json_conversion_type.py
  json_conversion_type.py
Labels: hacktoberfest-accepted

#23 Create python_logo.py
  python_logo.py
Labels: hacktoberfest-accepted

#31 Create enumerate.py
  Pogrammes/enumerate.py
Labels: hacktoberfest-accepted

#30 Create split.py
  Practice Problem/split.py
Labels: hacktoberfest-accepted

#29 Create map.py
  Pogrammes/map.py
Labels: hacktoberfest-accepted

#28 Create row-wise_element_additionin_tuple_matrix.py
  row-wise_element_additionin_tuple_matrix.py
Labels: hacktoberfest-accepted

#32 Create Iterators.py
  Pogrammes/Iterators.py
Labels: hacktoberfest-accepted

#33 Delete custom_iterators.py
  Pogrammes/custom_iterators.py
Labels: hacktoberfest-accepted

#34 Update 4.calculation.py
  Pogrammes/4.calculation.py
Labels: hacktoberfest-accepted

#35 Update 4.calculation.py
  Pogrammes/4.calculation.py
Labels: hacktoberfest-accepted

#36 Create alarm_clock_tkinter.py
  alarm_clock_tkinter.py
Labels: hacktoberfest-accepted

#37 Create 56.fabconii.py
  Pogrammes/56.fabconii.py
Labels: hacktoberfest-accepted

#38 Create github_scraper.py
  github_scraper.py
Labels: hacktoberfest-accepted

#39 Add files via upload
  SnowFall.py
Labels: hacktoberfest-accepted

#40 Added linear and binary search algorithms
  Search/binary.py
  Search/linear.py
Labels: hacktoberfest-accepted

#41 hactoberfest event
  sone_paper_scissor.py
Labels: hacktoberfest-accepted

#42 havtoberfest2022
  snake_game.py
Labels: hacktoberfest-accepted

#43 hactoberfest 2022
  dice.py
Labels: hacktoberfest-accepted

#44 Create 123.py
  123.py
Labels: hacktoberfest-accepted

#45 Create generateqr.py
  generateqr.py
Labels: hacktoberfest-accepted

#46 Create MinCostPath.py
  MinCostPath.py
Labels: hacktoberfest-accepted

#50 Update 8.area_of_triangle.py
  Practice Problem/8.area_of_triangle.py
Labels: hacktoberfest-accepted

#49 Update 6.area_of_square.py
  Practice Problem/6.area_of_square.py
Labels: hacktoberfest-accepted

#48 Update 14.leap_year.py
  Practice Problem/14.leap_year.py
Labels: hacktoberfest-accepted

#47 Update 15.1.patterns.py
  Practice Problem/15.1.patterns.py
Labels: hacktoberfest-accepted

#52 Update 24.factorial_numbers.py
  Practice Problem/24.factorial_numbers.py
Labels: hacktoberfest-accepted

#51 Update 10.odd_even.py
  Practice Problem/10.odd_even.py
Labels: hacktoberfest-accepted
